source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.1'


gem 'rails-api'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'
gem 'thin'
gem 'kramdown'

group :development, :test do
	gem 'pry'
	gem 'pry-byebug'
  gem 'rspec-rails', '~> 3.0.1'
  gem 'rspec_api_documentation', :git => 'https://github.com/zipmark/rspec_api_documentation', :ref => '96c8747'
  gem 'apitome'
end


# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
